# Generated by Django 4.1.4 on 2023-06-21 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width', models.IntegerField(blank=True, default=None, null=True)),
                ('height', models.IntegerField(blank=True, default=None, null=True)),
                ('svg_map', models.FileField(blank=True, default=None, null=True, upload_to='floor_images/')),
                ('png_map', models.FileField(blank=True, default=None, null=True, upload_to='floor_images/')),
                ('default_x_coordinate', models.IntegerField(blank=True, default=0)),
                ('default_y_coordinate', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('index_on_map', models.IntegerField(blank=True, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='workplace_booking.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'Свободно'), ('TAKEN', 'Занято'), ('YOURS', 'Забронировано вами'), ('BROKEN', 'Недоступно')], default='FREE', max_length=6, unique=True)),
                ('color', models.CharField(max_length=6, verbose_name='цвет в hex')),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('index', models.IntegerField()),
                ('column_id', models.IntegerField(blank=True, null=True)),
                ('row_id', models.IntegerField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='workplace_booking.room')),
            ],
            options={
                'unique_together': {('room', 'column_id', 'row_id')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='workplace_booking.workplace')),
            ],
        ),
    ]
