# Generated by Django 4.1.4 on 2023-06-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='area_x1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='area_x2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='area_y1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='area_y2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
